# Created using wingetcreate
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SevIQ.ThemeToggle
PackageVersion: 1.2.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/espensev/DarkToggle/releases/download/v1.2.0/ThemeToggle-Setup-1.2.0.exe
  InstallerSha256: 0019DFC4B32D63C1392AA264AED2253C1E0C2FB09216F8E2CC269BBFB8BB49B5
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
  ReleaseDate: 2024-12-24
ManifestType: installer
ManifestVersion: 1.10.0
